### ISSUE TITLE
[BUG] Cannot set provider & tikmate returns null URLs

### ISSUE THREAD

**Issue by frozenpandaman** [hansputera/tiktok-dl#99]
Glad the API endpoint is back up and running, thanks!

It seems the URL `type=` parameter, specified in the docs [here](https://docs.tdl.besecure.eu.org/getting-started/how-to-use) and [here](https://docs.tdl.besecure.eu.org/additional/provider), isn't working, e.g. 
```
https://tdl.besecure.eu.org/api/download?url=https://www.tiktok.com/@thembta/video/7117992666561809706&type=downtik&rotateOnError=true
```

returns a JSON with `"provider":"musicalydown"` instead of `downtik` like specified. It seems to be defaulting to a random provider, specific to each video.

This is problematic because the `tikmate` provider, when that one happens to be chosen, returns `"urls":[null]` meaning certain videos cannot be downloaded.

**Comment by hansputera** [comment]
Hello @frozenpandaman :wave:

Sorry for late response, can you test it again? I've fixed it on https://github.com/hansputera/tiktok-dl/commit/23cb390fe4b41f08dd500951b09191c49c4122f6, and https://github.com/hansputera/tiktok-dl/commit/7261fea7d9dafaf111c798efc092a2de30bb51c4

**Comment by hansputera** [comment]
Well, you can test the next version of TikTok-DL. 

`https://tiktok-next.herokuapp.com/api/video?url=<TIKTOK_VIDEO_URL>`
On this next version, I don't use a third party anymore. However, for now there are some issues such as not being able to get a response from the tiktok server, and sometimes there are unexpected errors.

**Comment by frozenpandaman** [comment]
@hansputera Using the tdl.besecure.eu.org URL in my original post, it still returns an incorrect provider – now it's giving `"provider":"lovetik"`, still not `downtik`. And in the cases it uses `getvidtik`, the URLs are null and the video cannot be downloaded. So it's still not fixed.

**Comment by frozenpandaman** [comment]
I tried the new version running on Heroku and it works great so far, thanks!!

FYI occasionally I am getting this response:
```json
{"_":"GetVideo","error":"dialing to the given TCP address timed out"}
```

**Comment by frozenpandaman** [comment]
I am also occasionally getting these errors:
```json
{"_":"GetVideo","error":"no response"}
```
and
```json
{"_":"GetVideo","error":"invalid character '\u003c' looking for beginning of value"}
```

**Comment by hansputera** [comment]
> @hansputera Using the tdl.besecure.eu.org URL in my original post, it still returns an incorrect provider – now it's giving `"provider":"lovetik"`, still not `downtik`. And in the cases it uses `getvidtik`, the URLs are null and the video cannot be downloaded. So it's still not fixed.

It should works now

1. downtik:
![image](https://user-images.githubusercontent.com/47862061/197336429-1fe3217f-91f2-4997-8c28-9dc4530b7374.png)

2. tikmate:
![image](https://user-images.githubusercontent.com/47862061/197336488-b3dc9757-0691-48f7-95f8-7b8a8e9b4637.png)

3. getvidtik:
![image](https://user-images.githubusercontent.com/47862061/197336526-e31dd79a-b3bb-4f9c-9768-9f528b496fb7.png)

**Comment by frozenpandaman** [comment]
@hansputera The `tiktok-next.herokuapp.com` endpoint now gives me an error:

https://www.herokucdn.com/error-pages/application-error.html

Let me know if you have a fix!

**Comment by hansputera** [comment]
> > @hansputera Using the tdl.besecure.eu.org URL in my original post, it still returns an incorrect provider – now it's giving `"provider":"lovetik"`, still not `downtik`. And in the cases it uses `getvidtik`, the URLs are null and the video cannot be downloaded. So it's still not fixed.
> 
> It should works now
> 
> 1. downtik:
>    ![image](https://user-images.githubusercontent.com/47862061/197336429-1fe3217f-91f2-4997-8c28-9dc4530b7374.png)
> 2. tikmate:
>    ![image](https://user-images.githubusercontent.com/47862061/197336488-b3dc9757-0691-48f7-95f8-7b8a8e9b4637.png)
> 3. getvidtik:
>    ![image](https://user-images.githubusercontent.com/47862061/197336526-e31dd79a-b3bb-4f9c-9768-9f528b496fb7.png)

I

**Comment by frozenpandaman** [comment]
> Sorry, since heroku doesn't offer free hosting again, the application is shutting down.

Thanks for the fast reply. Would you consider switching to Vercel or Netlify? Both have free tiers and seem to have largely superceded Heroku.

**Comment by frozenpandaman** [comment]
> Sorry, since heroku doesn't offer free hosting again, the application is shutting down.
 @hansputera Thanks for the fast reply. Would you consider switching to Vercel or Netlify? Both have free tiers and seem to have largely superceded Heroku.

Or, would you have instructions on how to run this on a local server?
